
apiVersion: v1
kind: Service
metadata:
  name: my-x86-service
  labels:
    app: my-x86-pod
spec:
  selector:
    app: my-x86-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: my-x86-pod
  labels:
    app: my-x86-pod
spec:
  containers:
  - name: nginx
    image: rezareza/nginx-multiarch:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 80
  nodeSelector:
    kubernetes.io/arch: amd64
---

apiVersion: v1
kind: Service
metadata:
  name: my-arm64-service
  labels:
    app: my-arm64-pod
spec:
  selector:
    app: my-arm64-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: my-arm64-pod
  labels:
    app: my-arm64-pod
spec:
  containers:
  - name: nginx
    image: rezareza/nginx-multiarch:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 80
  nodeSelector:
    kubernetes.io/arch: arm64
