FROM golang:alpine AS builder

WORKDIR /app

COPY src/main.go /app/

RUN go mod init secure
RUN go build -o /app/main

FROM alpine:latest

COPY --from=builder /app/main /app/main

CMD ["/app/main"]
